--------------------------------------------------------------------------------
-- AquaVitae — DDL Oracle (tabelas)
-- Gerado a partir do schema DBML do briefing do MVP.
-- Convenções: PKs com IDENTITY (exceto tabelas subtype, cujo bebida_id
-- é herdado de `bebida`), VARCHAR2(n CHAR) para suportar acentuação PT,
-- CLOB para texto livre, NUMBER(1) + CHECK para booleanos (sem tipo
-- BOOLEAN nativo em Oracle XE 18c/21c).
--
-- Nota de correção: `vinho_tipo.vinho_tipo_value` estava definido como
-- `integer` no DBML original — claramente inconsistente com as restantes
-- tabelas de lookup do mesmo padrão (vinho_corpo, vinho_tanino, etc., todas
-- VARCHAR2). Corrigido aqui para VARCHAR2(30 CHAR); sinalizado ao utilizador.
--
-- As foreign keys ficam em 02_constraints.sql (evita depender da ordem
-- de criação das tabelas).
--------------------------------------------------------------------------------

-- ============================================================
-- LOOKUPS GERAIS
-- ============================================================

CREATE TABLE utilizador_nationality (
    nationality_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nationality_value       VARCHAR2(30 CHAR),
    -- Código ISO 3166-1 alfa-2 do país (PT, ES, ...): a app desenha a bandeira a partir dele. Anulável: sem código, sem bandeira.
    nationality_codigo_pais VARCHAR2(2 CHAR) CONSTRAINT ck_nationality_codigo_pais CHECK (REGEXP_LIKE(nationality_codigo_pais, '^[A-Z]{2}$'))
);

CREATE TABLE avatar_categoria (
    avatar_categoria_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar_categoria_value  VARCHAR2(20 CHAR)
);

CREATE TABLE utilizador_avatar (
    avatar_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar_name           VARCHAR2(50 CHAR),
    avatar_category_id    NUMBER,
    avatar_path_image     VARCHAR2(255 CHAR),
    avatar_is_active      NUMBER(1) DEFAULT 1 CHECK (avatar_is_active IN (0, 1)),
    avatar_data_criacao   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE utilizador_role (
    utilizador_role_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_role_value  VARCHAR2(30 CHAR)
);

CREATE TABLE bebida_categoria (
    bebida_categoria_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bebida_categoria_value  VARCHAR2(40 CHAR) UNIQUE
);

CREATE TABLE pais (
    bebida_pais_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bebida_pais_value  VARCHAR2(60 CHAR) UNIQUE
);

CREATE TABLE produtor_pais (
    produtor_pais_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produtor_pais_value  VARCHAR2(60 CHAR) UNIQUE
);

CREATE TABLE retalhista_tipo (
    retalhista_tipo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retalhista_tipo_value  VARCHAR2(30 CHAR) UNIQUE
);

-- ============================================================
-- UTILIZADOR
-- ============================================================

CREATE TABLE utilizador (
    utilizador_id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_username              VARCHAR2(30 CHAR) UNIQUE,
    utilizador_first_name            VARCHAR2(25 CHAR),
    utilizador_last_name             VARCHAR2(40 CHAR),
    utilizador_email                 VARCHAR2(100 CHAR) UNIQUE,
    utilizador_password               VARCHAR2(160 CHAR),
    utilizador_nationality_id         NUMBER,
    utilizador_avatar_photo_id        NUMBER,
    utilizador_account_created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    utilizador_bio_desc               VARCHAR2(1000 CHAR),
    utilizador_role_id                NUMBER,
    -- Quando aceitou os termos e condições; NULL = nunca aceitou (a app mostra o popup). Só se guarda a data/hora: se os
    -- termos mudarem, quem aceitou antes de `aquavitae.termos.em-vigor-desde` volta a aceitar (ver API_ENDPOINTS.md).
    utilizador_termos_aceites_em      TIMESTAMP
);

CREATE TABLE utilizador_password_reset (
    utilizador_password_reset_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id                    NUMBER NOT NULL,
    codigo                            VARCHAR2(10 CHAR) NOT NULL,
    expira_em                         TIMESTAMP NOT NULL,
    usado                             NUMBER(1) DEFAULT 0 CHECK (usado IN (0, 1)),
    data_criacao                      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ============================================================
-- PRODUTOR / RETALHISTA
-- ============================================================

-- Região de um país (Douro, Rioja, Bordéus, ...): é o que o filtro "Origem" do catálogo mostra depois do país.
-- O 2.º UNIQUE (país, id) existe só para a FK composta de `produtor` (ver 02_constraints.sql): a região de um
-- produtor tem de ser do país desse produtor. O país é `produtor_pais` (mesmos ids que `pais`, ver database/README.md).
CREATE TABLE regiao (
    regiao_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regiao_nome     VARCHAR2(100 CHAR),
    regiao_pais_id  NUMBER,
    CONSTRAINT uq_regiao_pais_nome UNIQUE (regiao_pais_id, regiao_nome),
    CONSTRAINT uq_regiao_pais_id UNIQUE (regiao_pais_id, regiao_id)
);

CREATE TABLE produtor (
    produtor_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produtor_nome             VARCHAR2(150 CHAR),
    produtor_pais_id          NUMBER,
    produtor_regiao_id        NUMBER,
    produtor_historia         CLOB,
    produtor_ano_fundacao     NUMBER(4),
    produtor_website          VARCHAR2(255 CHAR),
    produtor_path_imagem      VARCHAR2(255 CHAR),
    -- Morada em texto livre (rua, código postal, localidade), para a página do produtor; NULL = não disponível.
    produtor_morada           VARCHAR2(300 CHAR),
    produtor_latitude         NUMBER(9,6),
    produtor_longitude        NUMBER(9,6),
    produtor_permite_visitas  NUMBER(1) DEFAULT 0 CHECK (produtor_permite_visitas IN (0, 1)),
    produtor_data_criacao     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE retalhista (
    retalhista_id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retalhista_nome                   VARCHAR2(100 CHAR),
    retalhista_path_logo              VARCHAR2(255 CHAR),
    retalhista_website                VARCHAR2(255 CHAR),
    retalhista_tipo_id                NUMBER,
    retalhista_rede_afiliados         VARCHAR2(50 CHAR),
    retalhista_codigo_afiliado        VARCHAR2(100 CHAR),
    retalhista_comissao_percentagem   NUMBER(5,2),
    retalhista_is_ativo               NUMBER(1) DEFAULT 1 CHECK (retalhista_is_ativo IN (0, 1)),
    retalhista_data_criacao           TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ============================================================
-- BEBIDA (supertype)
-- ============================================================

CREATE TABLE bebida (
    bebida_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bebida_category_id       NUMBER,
    bebida_name               VARCHAR2(150 CHAR),
    bebida_producer_id        NUMBER,
    bebida_pais_origem_id     NUMBER,
    bebida_ano_producao       NUMBER(4),
    bebida_teor_alcoolico     NUMBER(4,2),
    bebida_volume_ml          NUMBER,
    -- Caminho relativo (recurso estático do backend) OU URL absoluto (imagem do retalhista/feed): 1000 porque os URLs
    -- de imagem dos retalhistas levam parâmetros e passam facilmente dos 255.
    bebida_path_image         VARCHAR2(1000 CHAR),
    bebida_data_criacao       TIMESTAMP DEFAULT SYSTIMESTAMP,
    bebida_rating_medio       NUMBER(3,2) DEFAULT 0,
    bebida_total_reviews      NUMBER DEFAULT 0,
    -- GTIN da bebida (EAN-8, UPC-A/12, EAN-13 ou GTIN-14), em TEXTO (zeros à esquerda). Único: é como se reconhece a
    -- mesma bebida vinda de outro retalhista (só se junta um link novo). Anulável: nem todo o feed/página o traz
    -- (vários NULL são permitidos pelo UNIQUE). Não é exposto na API.
    bebida_ean                VARCHAR2(14 CHAR) CONSTRAINT ck_bebida_ean CHECK (REGEXP_LIKE(bebida_ean, '^[0-9]{8,14}$')),
    CONSTRAINT uq_bebida_ean UNIQUE (bebida_ean)
);

-- ============================================================
-- VINHO
-- ============================================================

CREATE TABLE casta_tipo (
    casta_tipo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casta_tipo_value  VARCHAR2(10 CHAR) UNIQUE -- 'Tinta' | 'Branca'
);

CREATE TABLE casta (
    casta_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casta_name      VARCHAR2(60 CHAR),
    casta_tipo_id    NUMBER -- separa as listas do filtro/onboarding (tinta/branca)
);

CREATE TABLE vinho_corpo (
    vinho_corpo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinho_corpo_value  VARCHAR2(30 CHAR) UNIQUE
);

CREATE TABLE vinho_tanino (
    vinho_tanino_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinho_tanino_value  VARCHAR2(60 CHAR) UNIQUE
);

CREATE TABLE vinho_tipo (
    vinho_tipo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinho_tipo_value  VARCHAR2(30 CHAR) -- corrigido de `integer` (ver nota no topo do ficheiro)
);

CREATE TABLE vinho (
    bebida_id             NUMBER PRIMARY KEY,
    vinho_casta_id         NUMBER,
    vinho_nivel_acidez     NUMBER(1) CHECK (vinho_nivel_acidez BETWEEN 1 AND 5),
    vinho_corpo_id         NUMBER,
    vinho_nivel_docura     NUMBER(1) CHECK (vinho_nivel_docura BETWEEN 1 AND 5),
    vinho_tanino_id        NUMBER,
    vinho_tipo_id          NUMBER
);

CREATE TABLE vinho_casta (
    vinho_casta_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinho_id                    NUMBER,
    casta_id                    NUMBER,
    vinho_casta_percentagem     NUMBER(5,2)
);

-- Barrica(s) em que o vinho estagiou: madeira (`cask`, partilhada com o whisky) + formato
-- (`cask_formato`: Bordeaux, Burgundy, Demi-Muid, ...) + meses de estágio. N:N, como vinho_casta.
CREATE TABLE vinho_cask (
    vinho_cask_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vinho_id                    NUMBER,
    cask_id                     NUMBER,
    cask_formato_id             NUMBER,
    vinho_cask_estagio_meses    NUMBER
);

-- ============================================================
-- WHISKY
-- ============================================================

CREATE TABLE whisky_tipo (
    whisky_tipo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whisky_tipo_value  VARCHAR2(30 CHAR) UNIQUE
);

CREATE TABLE whisky_corpo (
    whisky_corpo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whisky_corpo_value  VARCHAR2(20 CHAR)
);

-- Madeira da barrica. Partilhada: vinho_cask (vinho) e whisky_cask (whisky).
CREATE TABLE cask (
    cask_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cask_value   VARCHAR2(60 CHAR)
);

-- Formato da barrica (Bordeaux, Burgundy, Demi-Muid, ...), usado por vinho_cask.
CREATE TABLE cask_formato (
    cask_formato_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cask_formato_value   VARCHAR2(30 CHAR) UNIQUE
);

CREATE TABLE whisky (
    bebida_id             NUMBER PRIMARY KEY,
    whisky_tipo_id          NUMBER,
    whisky_regiao_id        NUMBER, -- FK para `regiao` (a mesma lista dos produtores); pode diferir da do produtor (engarrafador independente)
    whisky_corpo_id         NUMBER,
    whisky_idade            NUMBER,
    whisky_is_turfado       NUMBER(1) DEFAULT 0 CHECK (whisky_is_turfado IN (0, 1)),
    whisky_nivel_docura     NUMBER(1) CHECK (whisky_nivel_docura BETWEEN 1 AND 5),
    whisky_nivel_defumado   NUMBER(1) CHECK (whisky_nivel_defumado BETWEEN 1 AND 5)
);

CREATE TABLE whisky_cask (
    whisky_cask_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whisky_id                NUMBER,
    cask_id                  NUMBER,
    whisky_cask_estagio      NUMBER
);

-- ============================================================
-- GIN
-- ============================================================

CREATE TABLE gin_corpo (
    gin_corpo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gin_corpo_value  VARCHAR2(20 CHAR) UNIQUE
);

CREATE TABLE gin_destilacao (
    gin_destilacao_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gin_destilacao_value  VARCHAR2(40 CHAR)
);

CREATE TABLE botanico (
    botanico_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    botanico_name   VARCHAR2(50 CHAR)
);

CREATE TABLE gin (
    bebida_id                  NUMBER PRIMARY KEY,
    gin_tipo_destilacao_id       NUMBER,
    gin_corpo_id                 NUMBER,
    gin_nivel_docura             NUMBER(1) CHECK (gin_nivel_docura BETWEEN 1 AND 5)
);

CREATE TABLE gin_botanico (
    gin_botanico_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gin_id                NUMBER,
    botanico_id           NUMBER
);

-- ============================================================
-- LICOR
-- ============================================================

CREATE TABLE licor_base (
    licor_base_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licor_base_value  VARCHAR2(30 CHAR)
);

CREATE TABLE sabor_licor (
    sabor_licor_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sabor_licor_value  VARCHAR2(50 CHAR)
);

CREATE TABLE licor (
    bebida_id            NUMBER PRIMARY KEY,
    licor_base_id          NUMBER,
    licor_nivel_docura     NUMBER(1) CHECK (licor_nivel_docura BETWEEN 1 AND 5)
);

CREATE TABLE licor_sabor (
    licor_sabor_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licor_id             NUMBER,
    sabor_licor_id        NUMBER
);

-- ============================================================
-- VODKA
-- ============================================================

CREATE TABLE vodka_materia_prima (
    vodka_materia_prima_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vodka_materia_prima_value  VARCHAR2(30 CHAR) UNIQUE
);

CREATE TABLE vodka (
    bebida_id                  NUMBER PRIMARY KEY,
    vodka_materia_prima_id       NUMBER,
    vodka_num_destilacoes        NUMBER,
    vodka_nivel_suavidade        NUMBER(1) CHECK (vodka_nivel_suavidade BETWEEN 1 AND 5)
);

CREATE TABLE vodka_materia_prima_relation (
    vodka_materia_prima_relation_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vodka_id                              NUMBER,
    vodka_materia_prima_id                NUMBER
);

-- ============================================================
-- AGUARDENTE
-- ============================================================

CREATE TABLE aguardente_corpo (
    aguardente_corpo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aguardente_corpo_value  VARCHAR2(20 CHAR)
);

CREATE TABLE aguardente_tipo_cask (
    aguardente_tipo_cask_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aguardente_tipo_cask_value  VARCHAR2(50 CHAR)
);

CREATE TABLE aguardente_materia_prima (
    aguardente_materia_prima_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aguardente_materia_prima_value  VARCHAR2(30 CHAR)
);

CREATE TABLE aguardente (
    bebida_id                    NUMBER PRIMARY KEY,
    aguardente_materia_prima_id    NUMBER,
    aguardente_corpo_id            NUMBER,
    aguardente_idade_anos          NUMBER
);

CREATE TABLE aguardente_tipo_cask_relation (
    aguardente_tipo_cask_relation_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aguardente_id                          NUMBER,
    aguardente_tipo_cask_id                NUMBER,
    aguardente_tipo_cask_ordem_estagio     NUMBER
);

CREATE TABLE aguardente_materia_prima_relation (
    aguardente_materia_prima_relation_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aguardente_id                              NUMBER,
    aguardente_materia_prima_id                NUMBER
);

-- ============================================================
-- RELAÇÕES UTILIZADOR <-> BEBIDA
-- ============================================================

CREATE TABLE review (
    review_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bebida_id                   NUMBER,
    utilizador_id                NUMBER,
    rating_value                 NUMBER(2,1) CHECK (rating_value BETWEEN 0 AND 5),
    review_comment_value         VARCHAR2(4000 CHAR),
    review_data_criacao          TIMESTAMP DEFAULT SYSTIMESTAMP,
    review_data_atualizacao      TIMESTAMP,
    CONSTRAINT uq_review_bebida_utilizador UNIQUE (bebida_id, utilizador_id)
);

CREATE TABLE favorito (
    favorito_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id              NUMBER,
    bebida_id                  NUMBER,
    favorito_data_criacao      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE bebida_provada (
    bebida_provada_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id               NUMBER,
    bebida_id                   NUMBER,
    bebida_provada_data         TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE wishlist (
    wishlist_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id              NUMBER,
    bebida_id                  NUMBER,
    wishlist_data_criacao       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE cave (
    cave_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id          NUMBER,
    cave_nome               VARCHAR2(100 CHAR),
    cave_descricao          VARCHAR2(500 CHAR),
    cave_data_criacao       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE cave_bebida (
    cave_bebida_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cave_id                        NUMBER,
    bebida_id                      NUMBER,
    cave_bebida_quantidade          NUMBER DEFAULT 1,
    cave_bebida_data_aquisicao      DATE,
    cave_bebida_preco_pago          NUMBER(8,2),
    cave_bebida_janela_inicio       DATE,
    cave_bebida_janela_fim          DATE,
    cave_bebida_is_consumida        NUMBER(1) DEFAULT 0 CHECK (cave_bebida_is_consumida IN (0, 1)),
    cave_bebida_data_consumo        DATE,
    cave_bebida_notas               VARCHAR2(500 CHAR),
    cave_bebida_data_criacao        TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ============================================================
-- COMPRA / AFILIADOS
-- ============================================================

CREATE TABLE bebida_link_compra (
    bebida_link_compra_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bebida_id                           NUMBER,
    retalhista_id                       NUMBER,
    bebida_link_compra_url              VARCHAR2(500 CHAR),
    bebida_link_compra_preco_atual      NUMBER(8,2),
    bebida_link_compra_data_atualizacao TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Verificação diária de disponibilidade (ver backend/.../compra/LinkVerificacaoService).
    -- url_verificacao: página do produto SEM tracking, a que o job vai pedir — pedir o link de
    -- afiliado todos os dias contaria como cliques. Se for NULL e o retalhista tiver rede de
    -- afiliados, o link não é verificado; sem rede, usa-se url.
    bebida_link_compra_url_verificacao   VARCHAR2(500 CHAR),
    bebida_link_compra_is_ativo          NUMBER(1) DEFAULT 1 NOT NULL CHECK (bebida_link_compra_is_ativo IN (0, 1)),
    bebida_link_compra_data_verificacao  TIMESTAMP,
    bebida_link_compra_falhas_seguidas   NUMBER DEFAULT 0 NOT NULL,
    bebida_link_compra_data_indisponivel TIMESTAMP,
    bebida_link_compra_motivo            VARCHAR2(200 CHAR)
);

CREATE TABLE clique_compra (
    clique_compra_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id                  NUMBER,
    bebida_link_compra_id           NUMBER,
    clique_compra_data              TIMESTAMP DEFAULT SYSTIMESTAMP,
    clique_compra_is_perguntado     NUMBER(1) DEFAULT 0 CHECK (clique_compra_is_perguntado IN (0, 1)),
    clique_compra_resposta          VARCHAR2(20 CHAR)
);

-- ============================================================
-- PREFERÊNCIAS (onboarding)
-- ============================================================

CREATE TABLE utilizador_preferencia (
    utilizador_preferencia_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id                             NUMBER,
    utilizador_preferencia_acidez_min          NUMBER CHECK (utilizador_preferencia_acidez_min BETWEEN 1 AND 5),
    utilizador_preferencia_acidez_max          NUMBER CHECK (utilizador_preferencia_acidez_max BETWEEN 1 AND 5),
    utilizador_preferencia_docura_min          NUMBER CHECK (utilizador_preferencia_docura_min BETWEEN 1 AND 5),
    utilizador_preferencia_docura_max          NUMBER CHECK (utilizador_preferencia_docura_max BETWEEN 1 AND 5),
    utilizador_preferencia_data_atualizacao    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE utilizador_categoria_preferida (
    utilizador_categoria_preferida_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id                           NUMBER,
    bebida_categoria_id                     NUMBER
);

CREATE TABLE utilizador_casta_preferida (
    utilizador_casta_preferida_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id                       NUMBER,
    casta_id                            NUMBER
);
