--------------------------------------------------------------------------------
-- AquaVitae — Patch incremental (2026-09-17)
-- Suporte às decisões de backend/API_ENDPOINTS.md: castas tinta/branca (via
-- tabela de lookup, consistente com vinho_corpo/vinho_tanino/vinho_tipo) e
-- recuperação de password por código.
--
-- Só correr numa BD de DEV JÁ EXISTENTE (criada antes deste patch). Quem
-- reconstruir a BD do zero (docker compose down -v && up -d && run-migrations)
-- NÃO deve correr este ficheiro — 01_tables.sql/02_constraints.sql já incluem
-- estas alterações, e repetir causaria erro de coluna/tabela duplicada.
--
-- Uso manual (fora da sequência normal do run-migrations.ps1/.sh):
--   Get-Content ddl/04_patch_endpoints.sql -Raw | docker exec -i aquavitae-oracle-xe sqlplus -s "<user>/<pass>@//localhost:1521/XEPDB1"
--------------------------------------------------------------------------------

CREATE TABLE casta_tipo (
    casta_tipo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casta_tipo_value  VARCHAR2(10 CHAR) UNIQUE
);

ALTER TABLE casta ADD casta_tipo_id NUMBER;

ALTER TABLE casta ADD CONSTRAINT fk_casta_tipo
    FOREIGN KEY (casta_tipo_id) REFERENCES casta_tipo (casta_tipo_id);

INSERT INTO casta_tipo (casta_tipo_value) VALUES ('Tinta');
INSERT INTO casta_tipo (casta_tipo_value) VALUES ('Branca');

CREATE TABLE utilizador_password_reset (
    utilizador_password_reset_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id                    NUMBER NOT NULL,
    codigo                            VARCHAR2(10 CHAR) NOT NULL,
    expira_em                         TIMESTAMP NOT NULL,
    usado                             NUMBER(1) DEFAULT 0 CHECK (usado IN (0, 1)),
    data_criacao                      TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE utilizador_password_reset ADD CONSTRAINT fk_pwd_reset_utilizador
    FOREIGN KEY (utilizador_id) REFERENCES utilizador (utilizador_id);

-- Classifica as 10 castas já seedadas (as mesmas de seed/01_lookups.sql), por ID
-- para evitar problemas de encoding de acentos ao passar o SQL pelo docker exec.
UPDATE casta SET casta_tipo_id = (SELECT casta_tipo_id FROM casta_tipo WHERE casta_tipo_value = 'Tinta')  WHERE casta_id IN (1, 2, 3, 5, 8, 9);  -- Touriga Nacional, Touriga Franca, Tinta Roriz, Baga, Trincadeira, Castelão
UPDATE casta SET casta_tipo_id = (SELECT casta_tipo_id FROM casta_tipo WHERE casta_tipo_value = 'Branca') WHERE casta_id IN (4, 6, 7, 10); -- Alvarinho, Arinto, Fernão Pires, Loureiro

COMMIT;
