--------------------------------------------------------------------------------
-- AquaVitae — Patch incremental (2026-09-19)
-- Aplica a uma BD de DEV JÁ EXISTENTE as notas de seed do utilizador
-- (android/AQUAVITAESEEDS-NOTES -> database/seed/01_lookups.sql):
--   1. Schema novo: cask_formato + vinho_cask (barrica do vinho: madeira + formato + estágio).
--   2. Lookups com os valores das notas — rename/remap NO SÍTIO, para os ids e as relações dos
--      dados demo ficarem intactos (botânicos passam a famílias, destilação do gin, sabores, ...).
--   3. Países (nas duas tabelas, com ids alinhados) e castas completos.
--
-- Só correr numa BD de DEV criada antes deste patch (quem reconstruir a BD do zero já tem tudo em
-- 01_tables.sql / 02_constraints.sql / seed/01_lookups.sql). Tal como 04/05, NÃO faz parte da sequência do
-- run-migrations.ps1/.sh. É repetível: todos os passos ignoram o que já existe. Falha (e reverte o DML)
-- se, no fim, `pais` e `produtor_pais` não ficarem com os mesmos ids.
--
-- Uso manual (com NLS_LANG, ver database/README.md). Envia sempre o ficheiro, nunca SQL inline:
--   docker cp ddl/06_patch_seed_notas.sql aquavitae-oracle-xe:/tmp/06.sql
--   docker exec -e NLS_LANG=AMERICAN_AMERICA.AL32UTF8 aquavitae-oracle-xe sqlplus -s "<user>/<pass>@//localhost:1521/XEPDB1" @/tmp/06.sql
--------------------------------------------------------------------------------

WHENEVER SQLERROR EXIT FAILURE ROLLBACK

-- ============================================================
-- 1. SCHEMA NOVO — barrica do vinho
-- ============================================================

DECLARE
  -- Executa DDL ignorando "já existe" (ORA-00955 tabela; ORA-02264 / ORA-02275 constraint):
  -- torna este passo repetível, mesmo que uma tentativa anterior tenha parado a meio.
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-955, -2264, -2275) THEN
        RAISE;
      END IF;
  END ddl;
BEGIN
  ddl('CREATE TABLE cask_formato (
         cask_formato_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         cask_formato_value   VARCHAR2(30 CHAR) UNIQUE
       )');
  ddl('CREATE TABLE vinho_cask (
         vinho_cask_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         vinho_id                    NUMBER,
         cask_id                     NUMBER,
         cask_formato_id             NUMBER,
         vinho_cask_estagio_meses    NUMBER
       )');
  ddl('ALTER TABLE vinho_cask ADD CONSTRAINT fk_vinho_cask_vinho
         FOREIGN KEY (vinho_id) REFERENCES vinho (bebida_id)');
  ddl('ALTER TABLE vinho_cask ADD CONSTRAINT fk_vinho_cask_cask
         FOREIGN KEY (cask_id) REFERENCES cask (cask_id)');
  ddl('ALTER TABLE vinho_cask ADD CONSTRAINT fk_vinho_cask_formato
         FOREIGN KEY (cask_formato_id) REFERENCES cask_formato (cask_formato_id)');
END;
/

-- ============================================================
-- 2. REMAPEAMENTOS — valores que os dados demo usam e as notas trocam.
--    Rename no sítio (ids e relações intactos). Os DELETE só apagam valores sem qualquer uso.
-- ============================================================

-- Países
UPDATE pais SET bebida_pais_value = 'Estados Unidos da América' WHERE bebida_pais_value = 'Estados Unidos';

-- Vinho: 'Verde' (fora das notas, nenhum vinho o usa) passa a 'Frisante'
UPDATE vinho_tipo SET vinho_tipo_value = 'Frisante' WHERE vinho_tipo_value = 'Verde';

-- Casta: Aragonez = Tinta Roriz (a mesma casta) — uma só linha com os dois nomes
UPDATE casta SET casta_name = 'Aragonez (Tinta Roriz)' WHERE casta_name = 'Tinta Roriz';

-- Cask: os 4 placeholders de whisky saem (não há whiskies); entram as madeiras do vinho (passo 3)
DELETE FROM cask c
 WHERE c.cask_value IN ('Ex-Bourbon', 'Ex-Sherry', 'Ex-Vinho do Porto', 'Carvalho Novo')
   AND NOT EXISTS (SELECT 1 FROM whisky_cask w WHERE w.cask_id = c.cask_id);

-- Whisky
UPDATE whisky_tipo SET whisky_tipo_value = 'Blended Scotch' WHERE whisky_tipo_value = 'Blended';

-- Gin: destilação
UPDATE gin_destilacao SET gin_destilacao_value = 'Alambique' WHERE gin_destilacao_value = 'Pot Still';
UPDATE gin_destilacao SET gin_destilacao_value = 'Infusão de Vapor' WHERE gin_destilacao_value = 'Vapor Infusion';
DELETE FROM gin_destilacao d
 WHERE d.gin_destilacao_value = 'Column Still'
   AND NOT EXISTS (SELECT 1 FROM gin g WHERE g.gin_tipo_destilacao_id = d.gin_destilacao_id);

-- Gin: botânicos passam a famílias aromáticas
UPDATE botanico SET botanico_name = 'Citrino' WHERE botanico_name = 'Casca de Citrinos';
UPDATE botanico SET botanico_name = 'Especiaria e Picante' WHERE botanico_name = 'Coentros';
UPDATE botanico SET botanico_name = 'Herbáceo e Verde' WHERE botanico_name = 'Alecrim';
UPDATE botanico SET botanico_name = 'Floral' WHERE botanico_name = 'Alfazema';
-- Erva-príncipe (capim-limão), usada por 1 gin demo, passa a Citrino
UPDATE gin_botanico
   SET botanico_id = (SELECT botanico_id FROM botanico WHERE botanico_name = 'Citrino')
 WHERE botanico_id = (SELECT botanico_id FROM botanico WHERE botanico_name = 'Erva-Príncipe');
DELETE FROM botanico b
 WHERE b.botanico_name IN ('Erva-Príncipe', 'Cardamomo')
   AND NOT EXISTS (SELECT 1 FROM gin_botanico gb WHERE gb.botanico_id = b.botanico_id);

-- Licor: base
UPDATE licor_base SET licor_base_value = 'Vínica' WHERE licor_base_value = 'Aguardente Vínica';
UPDATE licor_base SET licor_base_value = 'Neutra' WHERE licor_base_value = 'Álcool Neutro';
-- As 2 ginjinhas demo tinham a base 'Aguardente de Cereja', sem equivalente nas notas: NULL = "não disponível"
UPDATE licor
   SET licor_base_id = NULL
 WHERE licor_base_id = (SELECT licor_base_id FROM licor_base WHERE licor_base_value = 'Aguardente de Cereja');
DELETE FROM licor_base b
 WHERE b.licor_base_value IN ('Aguardente de Cereja', 'Aguardente Bagaceira')
   AND NOT EXISTS (SELECT 1 FROM licor l WHERE l.licor_base_id = b.licor_base_id);

-- Licor: sabores
UPDATE sabor_licor SET sabor_licor_value = 'Ervas e Especiarias' WHERE sabor_licor_value = 'Ervas';
DELETE FROM sabor_licor s
 WHERE s.sabor_licor_value = 'Citrinos'
   AND NOT EXISTS (SELECT 1 FROM licor_sabor x WHERE x.sabor_licor_id = s.sabor_licor_id);

-- Aguardente: base (medronho é fruta; 'Bagaço de Uva' mantém-se)
UPDATE aguardente_materia_prima SET aguardente_materia_prima_value = 'Fruta' WHERE aguardente_materia_prima_value = 'Medronho';
UPDATE aguardente_materia_prima SET aguardente_materia_prima_value = 'Cana de Açúcar' WHERE aguardente_materia_prima_value = 'Cana-de-açúcar';
DELETE FROM aguardente_materia_prima m
 WHERE m.aguardente_materia_prima_value = 'Cereja'
   AND NOT EXISTS (SELECT 1 FROM aguardente a WHERE a.aguardente_materia_prima_id = m.aguardente_materia_prima_id)
   AND NOT EXISTS (SELECT 1 FROM aguardente_materia_prima_relation r WHERE r.aguardente_materia_prima_id = m.aguardente_materia_prima_id);

-- Aguardente: cask ('Inox (sem estágio)' deixa de existir: sem barrica = sem linhas na relação)
UPDATE aguardente_tipo_cask SET aguardente_tipo_cask_value = 'Carvalho' WHERE aguardente_tipo_cask_value = 'Carvalho Novo';
UPDATE aguardente_tipo_cask SET aguardente_tipo_cask_value = 'Ex-Vinho' WHERE aguardente_tipo_cask_value = 'Ex-Vinho do Porto';
DELETE FROM aguardente_tipo_cask c
 WHERE c.aguardente_tipo_cask_value = 'Inox (sem estágio)'
   AND NOT EXISTS (SELECT 1 FROM aguardente_tipo_cask_relation r WHERE r.aguardente_tipo_cask_id = c.aguardente_tipo_cask_id);

-- ============================================================
-- 3. VALORES NOVOS DAS NOTAS (só os que ainda não existem, pela ordem das notas)
-- ============================================================

DECLARE
  TYPE t_lista IS TABLE OF VARCHAR2(60 CHAR);

  PROCEDURE garantir(p_tabela VARCHAR2, p_coluna VARCHAR2, p_valores t_lista) IS
  BEGIN
    FOR i IN 1 .. p_valores.COUNT LOOP
      EXECUTE IMMEDIATE
        'INSERT INTO ' || p_tabela || ' (' || p_coluna || ') SELECT :1 FROM dual ' ||
        'WHERE NOT EXISTS (SELECT 1 FROM ' || p_tabela || ' WHERE ' || p_coluna || ' = :2)'
        USING p_valores(i), p_valores(i);
    END LOOP;
  END garantir;
BEGIN
  garantir('vinho_tipo', 'vinho_tipo_value',
    t_lista('Tinto', 'Branco', 'Rosé', 'Espumante', 'Frisante', 'Generoso', 'Sobremesa'));
  garantir('cask', 'cask_value',
    t_lista('Carvalho Francês', 'Carvalho Americano', 'Carvalho Húngaro', 'Carvalho Esloveno', 'Acácia', 'Castanheiro'));
  garantir('cask_formato', 'cask_formato_value',
    t_lista('Bordeaux', 'Burgundy', 'Demi-Muid', 'Tonel', 'Balseiro', 'Foudre', 'Oval'));
  garantir('whisky_tipo', 'whisky_tipo_value',
    t_lista('Single Malt', 'Single Grain', 'Blended Scotch', 'Blended Malt', 'Bourbon', 'Rye', 'Tennessee'));
  garantir('whisky_regiao', 'whisky_regiao_nome',
    t_lista('Speyside', 'Highlands', 'Islay', 'Lowlands', 'Campbeltown', 'Islands', 'Kentucky', 'Tennessee',
            'Irlanda', 'Japão', 'Canadá', 'Índia', 'Taiwan', 'Austrália', 'Portugal', 'Espanha'));
  garantir('gin_destilacao', 'gin_destilacao_value',
    t_lista('Alambique', 'Infusão de Vapor', 'Vácuo', 'Composto'));
  garantir('botanico', 'botanico_name',
    t_lista('Zimbro', 'Citrino', 'Especiaria e Picante', 'Floral', 'Herbáceo e Verde', 'Terroso', 'Frutado'));
  garantir('licor_base', 'licor_base_value',
    t_lista('Neutra', 'Vodka', 'Vínica', 'Rum', 'Whisky', 'Tequila', 'Mezcal'));
  garantir('sabor_licor', 'sabor_licor_value',
    t_lista('Cereja', 'Limoncello', 'Frutos do Bosque', 'Pêssego', 'Laranja', 'Banana', 'Maracujá',
            'Ervas e Especiarias', 'Frutos Secos', 'Chocolate', 'Amêndoa', 'Baunilha', 'Cremosos',
            'Medronho', 'Amora', 'Mirtilo', 'Groselha'));
  garantir('vodka_materia_prima', 'vodka_materia_prima_value',
    t_lista('Trigo', 'Centeio', 'Cevada', 'Milho', 'Arroz', 'Batata', 'Mandioca', 'Cana de Açúcar',
            'Melaço', 'Fruta', 'Beterraba Sacarina', 'Soro de Leite'));
  garantir('aguardente_materia_prima', 'aguardente_materia_prima_value',
    t_lista('Fruta', 'Cereal', 'Cana de Açúcar', 'Agave', 'Tubérculo', 'Bagaço de Uva', 'Vinho'));
  garantir('aguardente_tipo_cask', 'aguardente_tipo_cask_value',
    t_lista('Carvalho', 'Carvalho Americano', 'Carvalho Francês', 'Carvalho do Leste Europeu', 'Madeira Nativa',
            'Amburana', 'Bálsamo', 'Jequitibá', 'Castanheira', 'Ipê', 'Pau-Brasil', 'Segundo-Uso',
            'Ex-Bourbon', 'Ex-Xerez', 'Ex-Vinho'));
END;
/

-- ============================================================
-- 4. PAÍSES — a mesma lista em `pais` e `produtor_pais`, com os MESMOS ids.
--    `pais` é a referência: acrescenta-se o que falta (ids por defeito) e `produtor_pais` copia-o com
--    ids EXPLÍCITOS. Não dá para confiar em "inserir nas duas pela mesma ordem": os identity das duas
--    tabelas deixam de ser iguais assim que há inserts revertidos, cache ou reinícios da BD (na dev
--    estavam ambos em 241 com máximos 8 e 5). Depois reinicia-se o identity das duas em MAX+1, para
--    inserts futuros sem id não colidirem.
-- ============================================================

DECLARE
  TYPE t_lista IS TABLE OF VARCHAR2(60 CHAR);
  v_paises t_lista := t_lista(
    'Portugal',
    'Espanha',
    'França',
    'Escócia',
    'Itália',
    'Estados Unidos da América',
    'Reino Unido',
    'Alemanha',
    'Abecásia',
    'Afeganistão',
    'África do Sul',
    'Albânia',
    'Andorra',
    'Angola',
    'Antígua e Barbuda',
    'Arábia Saudita',
    'Argélia',
    'Argentina',
    'Arménia',
    'Aruba',
    'Austrália',
    'Áustria',
    'Azerbaijão',
    'Bahamas',
    'Bahrein',
    'Bangladesh',
    'Barbados',
    'Bélgica',
    'Belize',
    'Benim',
    'Bermudas',
    'Bielorrússia',
    'Bolívia',
    'Bósnia e Herzegovina',
    'Botswana',
    'Brasil',
    'Brunei',
    'Bulgária',
    'Burkina Faso',
    'Burundi',
    'Butão',
    'Cabo Verde',
    'Camarões',
    'Camboja',
    'Canadá',
    'Catar',
    'Cazaquistão',
    'Chade',
    'Chile',
    'China',
    'Chipre',
    'Singapura',
    'Colômbia',
    'Comores',
    'Coreia do Norte',
    'Coreia do Sul',
    'Costa do Marfim',
    'Costa Rica',
    'Croácia',
    'Cuba',
    'Curaçau',
    'Dinamarca',
    'Djibouti',
    'Dominica',
    'Egito',
    'El Salvador',
    'Emirados Árabes Unidos',
    'Equador',
    'Eritreia',
    'Eslováquia',
    'Eslovénia',
    'Estónia',
    'Essuatíni',
    'Etiópia',
    'Fiji',
    'Filipinas',
    'Finlândia',
    'Gabão',
    'Gâmbia',
    'Gana',
    'Geórgia',
    'Granada',
    'Grécia',
    'Gronelândia',
    'Guadalupe',
    'Guiana Francesa',
    'Guatemala',
    'Guiana',
    'Guiné',
    'Guiné-Bissau',
    'Guiné Equatorial',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Hungria',
    'Iémen',
    'Índia',
    'Indonésia',
    'Inglaterra',
    'Ilhas Caimão',
    'Ilhas Marianas do Norte',
    'Ilhas Virgens',
    'Irão',
    'Iraque',
    'Irlanda do Norte',
    'Irlanda',
    'Islândia',
    'Israel',
    'Jamaica',
    'Japão',
    'Jordânia',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letónia',
    'Líbano',
    'Libéria',
    'Líbia',
    'Liechtenstein',
    'Lituânia',
    'Luxemburgo',
    'Macedónia do Norte',
    'Macau',
    'Madagascar',
    'Malásia',
    'Malawi',
    'Maldivas',
    'Mali',
    'Malta',
    'Marrocos',
    'Ilhas Marshall',
    'Maurícia',
    'Mauritânia',
    'México',
    'Mianmar',
    'Micronésia',
    'Moçambique',
    'Moldávia',
    'Mónaco',
    'Mongólia',
    'Montenegro',
    'Namíbia',
    'Nauru',
    'Nepal',
    'Nicarágua',
    'Níger',
    'Nigéria',
    'Noruega',
    'Nova Zelândia',
    'Omã',
    'Ossétia do Sul',
    'País de Gales',
    'Países Baixos',
    'Palau',
    'Palestina',
    'Panamá',
    'Papua-Nova Guiné',
    'Paquistão',
    'Paraguai',
    'Peru',
    'Polónia',
    'Polinésia Francesa',
    'Porto Rico',
    'Quénia',
    'Quirguistão',
    'República Árabe Saaraui Democrática',
    'República Centro-Africana',
    'República Democrática do Congo',
    'República do Congo',
    'República Dominicana',
    'República Checa',
    'República Turca de Chipre do Norte',
    'Roménia',
    'Ruanda',
    'Rússia',
    'Ilhas Salomão',
    'Samoa',
    'San Marino',
    'Santa Lúcia',
    'São Cristóvão e Neves',
    'São Tomé e Príncipe',
    'São Vicente e Granadinas',
    'Senegal',
    'Serra Leoa',
    'Sérvia',
    'Seychelles',
    'Síria',
    'Somália',
    'Sri Lanka',
    'Sudão do Sul',
    'Sudão',
    'Suécia',
    'Suíça',
    'Suriname',
    'Tailândia',
    'Taiwan',
    'Tajiquistão',
    'Tanzânia',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad e Tobago',
    'Tunísia',
    'Turquemenistão',
    'Turquia',
    'Tuvalu',
    'Ucrânia',
    'Uganda',
    'Uruguai',
    'Uzbequistão',
    'Vanuatu',
    'Vaticano',
    'Venezuela',
    'Vietname',
    'Zâmbia',
    'Zimbábue'

  );
  v_desalinhados NUMBER;
BEGIN
  FOR i IN 1 .. v_paises.COUNT LOOP
    INSERT INTO pais (bebida_pais_value)
      SELECT v_paises(i) FROM dual WHERE NOT EXISTS (SELECT 1 FROM pais WHERE bebida_pais_value = v_paises(i));
  END LOOP;

  INSERT INTO produtor_pais (produtor_pais_id, produtor_pais_value)
    SELECT a.bebida_pais_id, a.bebida_pais_value
      FROM pais a
     WHERE NOT EXISTS (SELECT 1 FROM produtor_pais p WHERE p.produtor_pais_id = a.bebida_pais_id);

  SELECT COUNT(*) INTO v_desalinhados
    FROM pais a FULL OUTER JOIN produtor_pais b
      ON b.produtor_pais_id = a.bebida_pais_id AND b.produtor_pais_value = a.bebida_pais_value
   WHERE a.bebida_pais_id IS NULL OR b.produtor_pais_id IS NULL;
  IF v_desalinhados > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'pais e produtor_pais desalinhados: ' || v_desalinhados || ' linha(s)');
  END IF;

  EXECUTE IMMEDIATE 'ALTER TABLE pais MODIFY (bebida_pais_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
  EXECUTE IMMEDIATE 'ALTER TABLE produtor_pais MODIFY (produtor_pais_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
END;
/

-- ============================================================
-- 5. CASTAS (as 3 entradas "de enchimento" das notas ficam de fora)
-- ============================================================

DECLARE
  TYPE t_lista IS TABLE OF VARCHAR2(60 CHAR);
  v_tinta   casta_tipo.casta_tipo_id%TYPE;
  v_branca  casta_tipo.casta_tipo_id%TYPE;
  v_tintas  t_lista := t_lista(
    'Alcoa',
    'Alfrocheiro',
    'Alicante Bouschet',
    'Alvarelhão',
    'Alvarelhão Ceitão',
    'Amaral',
    'Amor-Não-Me-Deixes',
    'Amostrinha',
    'Aragonez (Tinta Roriz)',
    'Aramon',
    'Arjunção',
    'Baga',
    'Barca',
    'Barreto',
    'Bastardo',
    'Bastardo Tinto',
    'Bonvedro',
    'Borraçal',
    'Bragão',
    'Branjo',
    'Cabinda',
    'Caladoc',
    'Calrão',
    'Camarate',
    'Campanário',
    'Carrega Burros',
    'Carrega Tinto',
    'Casculho',
    'Castelã',
    'Castelão',
    'Castelino',
    'Cidadelhe',
    'Cidreiro',
    'Complexa',
    'Concieira',
    'Coração de Galo',
    'Cornifesto',
    'Corropio',
    'Corvo',
    'Deliciosa',
    'Doçal',
    'Doce',
    'Donzelinho Tinto',
    'Engomada',
    'Esgana Cão Tinto',
    'Espadeiro',
    'Espadeiro Mole',
    'Farinheira',
    'Fepiro',
    'Ferral',
    'Galego',
    'Gonçalo Pires',
    'Gorda',
    'Gouveio Preto',
    'Graciosa',
    'Grangeal',
    'Grossa',
    'Jaen',
    'Lourela',
    'Lusitano',
    'Malandra',
    'Malvarisco',
    'Malvasia Preta',
    'Manteúdo Preto',
    'Mário Feld',
    'Marufo',
    'Melhorio',
    'Melra',
    'Mindelo',
    'Molar',
    'Monvedro',
    'Moreto',
    'Moscargo',
    'Moscatel Galego Tinto',
    'Mourisco',
    'Mourisco de Semente',
    'Mourisco de Trevões',
    'Mulata',
    'Negra Mole',
    'Nevoeira',
    'Padeiro',
    'Parreira Matias',
    'Patorra',
    'Pau Ferro',
    'Pedral',
    'Pero Pinhão',
    'Péxem',
    'Pical',
    'Pilongo',
    'Português Azul',
    'Preto Cardana',
    'Preto Martinho',
    'Primavera',
    'Rabo de Anho',
    'Rabo de Lobo',
    'Rabo de Ovelha Tinto',
    'Ramisco',
    'Ramisco Tinto',
    'Ricoca',
    'Rodo',
    'Roseira',
    'Rufete',
    'Saborinho',
    'Santareno',
    'São Saul',
    'Sevilhão',
    'Sousão',
    'Tinta',
    'Tinta Aguiar',
    'Tinta Aurélio',
    'Tinta Barroca',
    'Tinta Bastardinha',
    'Tinta Caiada',
    'Tinta Carvalha',
    'Tinta Fontes',
    'Tinta Francisca',
    'Tinta Lameira',
    'Tinta Lisboa',
    'Tinta Martins',
    'Tinta Mesquita',
    'Tinta Miúda',
    'Tinta Negra',
    'Tinta Penajóia',
    'Tinta Pereira',
    'Tinta Pomar',
    'Tinta Porto Santo',
    'Tinta Tabuaço',
    'Tintem',
    'Tintinha',
    'Tinto-cão',
    'Tinto Pegões',
    'Touriga Fêmea',
    'Touriga Franca',
    'Touriga Nacional',
    'Transâncora',
    'Trincadeira',
    'Triunfo',
    'Valbom',
    'Valdosa',
    'Varejoa',
    'Verdelho Tinto',
    'Verdial Tinto',
    'Vinhão',
    'Xara',
    'Zé do Telheiro'

  );
  v_brancas t_lista := t_lista(
    'Alicante Branco',
    'Almafra',
    'Almenhaca',
    'Antão Vaz',
    'Alvadurão',
    'Alvarinho',
    'Alvar',
    'Alvarelhão Branco',
    'Arinto',
    'Arinto do Interior',
    'Avesso',
    'Azal',
    'Babosa',
    'Barcelo',
    'Bastardo Branco',
    'Batoca',
    'Beba',
    'Bical',
    'Boal Barreiro',
    'Boal Branco',
    'Boal Espinho',
    'Branca de Anadia',
    'Branco Gouvães',
    'Branco Guimarães',
    'Branco João',
    'Branda',
    'Budelho',
    'Caínho',
    'Caracol',
    'Caramela',
    'Carão de Moça',
    'Carrasquenho',
    'Carrega Branco',
    'Cascal',
    'Castália',
    'Castelão Branco',
    'Castelo Branco',
    'Casteloa',
    'Cerceal Branco',
    'Cercial',
    'Côdega de Larinho',
    'Corval',
    'Crato Espanhol',
    'Dedo-de-Dama',
    'Diagalves',
    'Dona-branca',
    'Dona-joaquina',
    'Donzelinho Branco',
    'Dorinto',
    'Encruzado',
    'Esganinho',
    'Esganoso',
    'Estreito Macio',
    'Fernão Pires',
    'Folgasão',
    'Folha de Figueira',
    'Fonte Cal',
    'Galego Dourado',
    'Generosa',
    'Gigante',
    'Godelho',
    'Gouveio',
    'Gouveio Estimado',
    'Gouveio Real',
    'Granho',
    'Lameiro',
    'Larião',
    'Leira',
    'Lilás',
    'Loureiro',
    'Luzidio',
    'Malvasia',
    'Malvasia Bianca',
    'Malvasia Branca',
    'Malvasia Branca de S. Jorge',
    'Malvasia Cândida',
    'Malvasia Fina/Boal',
    'Malvasia Parda',
    'Malvasia Rei',
    'Malvasia Romana',
    'Malvia',
    'Malvoeira',
    'Manteúdo',
    'Marquinhas',
    'Molinha',
    'Moscatel Galego Branco',
    'Moscatel Graúdo',
    'Moscatel Nunes',
    'Mourisco Branco',
    'Naia',
    'Pé Comprido',
    'Perigo',
    'Perrum',
    'Pinheira Branca',
    'Pintosa',
    'Praça',
    'Promissão',
    'Rabigato',
    'Rabigato Franco',
    'Rabigato Moreno',
    'Rabo de Ovelha',
    'Ratinho',
    'Roupeiro Branco',
    'Sabro',
    'Samarrinho',
    'Santoal',
    'São Mamede',
    'Sarigo',
    'Seara Nova',
    'Semilão',
    'Sercial',
    'Sercialinho',
    'Síria',
    'Tália',
    'Tamarez',
    'Terrantês',
    'Terrantez da Terceira',
    'Terrantez do Pico',
    'Touriga Branca',
    'Trajadura',
    'Trincadeira Branca',
    'Trincadeira-das-pratas',
    'Uva Cão',
    'Uva Cavaco',
    'Uva Salsa',
    'Valente',
    'Valveirinho',
    'Vencedor',
    'Verdelho',
    'Verdial Branco',
    'Viosinho',
    'Vital'

  );
BEGIN
  SELECT casta_tipo_id INTO v_tinta  FROM casta_tipo WHERE casta_tipo_value = 'Tinta';
  SELECT casta_tipo_id INTO v_branca FROM casta_tipo WHERE casta_tipo_value = 'Branca';
  FOR i IN 1 .. v_tintas.COUNT LOOP
    INSERT INTO casta (casta_name, casta_tipo_id)
      SELECT v_tintas(i), v_tinta FROM dual WHERE NOT EXISTS (SELECT 1 FROM casta WHERE casta_name = v_tintas(i));
  END LOOP;
  FOR i IN 1 .. v_brancas.COUNT LOOP
    INSERT INTO casta (casta_name, casta_tipo_id)
      SELECT v_brancas(i), v_branca FROM dual WHERE NOT EXISTS (SELECT 1 FROM casta WHERE casta_name = v_brancas(i));
  END LOOP;
END;
/

COMMIT;
EXIT
