--------------------------------------------------------------------------------
-- AquaVitae — Patch incremental (2026-09-19)
-- Regiões como lookup (decisão do utilizador, "opção B"): tabela `regiao` (país + nome) e `produtor` passa a
-- apontar para ela (`produtor_regiao_id`) em vez do texto livre `produtor_regiao`.
--   1. Schema: `regiao` e `produtor.produtor_regiao_id`.
--   2. Regiões dos países mais populares (as mesmas de seed/01_lookups.sql).
--   3. Migra os produtores existentes do texto para a região e apaga a coluna de texto. Os valores compostos
--      ("Vinho Verde — Melgaço") passam à região (a localidade perde-se); os sem correspondência (Peniche,
--      Lousã — Beira Litoral) ficam NULL = "não disponível" e são listados antes de a coluna ser apagada.
--   4. FK composta (a região de um produtor tem de ser do país desse produtor) + CHECK.
--
-- Só correr numa BD de DEV criada antes deste patch (quem reconstruir a BD do zero já tem tudo em 01_tables.sql /
-- 02_constraints.sql / seed). Tal como 04 a 06, NÃO faz parte do run-migrations. É repetível: cada passo ignora o
-- que já existe. Se falhar, reverte o DML (o DDL já executado fica; volta a correr sem problema).
--
-- Uso manual (com NLS_LANG, ver database/README.md). Envia sempre o ficheiro, nunca SQL inline:
--   docker cp ddl/07_patch_regioes.sql aquavitae-oracle-xe:/tmp/07.sql
--   docker exec -e NLS_LANG=AMERICAN_AMERICA.AL32UTF8 aquavitae-oracle-xe sqlplus -s "<user>/<pass>@//localhost:1521/XEPDB1" @/tmp/07.sql
--------------------------------------------------------------------------------

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

-- ============================================================
-- 1. SCHEMA
-- ============================================================

DECLARE
  -- Ignora "já existe" (ORA-00955 tabela; ORA-01430 coluna; ORA-02261/02264/02275 constraints).
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-955, -1430, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END ddl;
BEGIN
  ddl('CREATE TABLE regiao (
         regiao_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         regiao_nome     VARCHAR2(100 CHAR),
         regiao_pais_id  NUMBER,
         CONSTRAINT uq_regiao_pais_nome UNIQUE (regiao_pais_id, regiao_nome),
         CONSTRAINT uq_regiao_pais_id UNIQUE (regiao_pais_id, regiao_id)
       )');
  ddl('ALTER TABLE regiao ADD CONSTRAINT fk_regiao_pais
         FOREIGN KEY (regiao_pais_id) REFERENCES produtor_pais (produtor_pais_id)');
  ddl('ALTER TABLE produtor ADD (produtor_regiao_id NUMBER)');
END;
/

-- ============================================================
-- 2. REGIÕES (lista provisória, a rever — ver comentário em seed/01_lookups.sql)
-- ============================================================

DECLARE
  TYPE t_lista IS TABLE OF VARCHAR2(100 CHAR);

  PROCEDURE regioes(p_pais VARCHAR2, p_nomes t_lista) IS
    v_pais produtor_pais.produtor_pais_id%TYPE;
  BEGIN
    SELECT produtor_pais_id INTO v_pais FROM produtor_pais WHERE produtor_pais_value = p_pais;
    FOR i IN 1 .. p_nomes.COUNT LOOP
      INSERT INTO regiao (regiao_nome, regiao_pais_id)
        SELECT p_nomes(i), v_pais FROM dual
         WHERE NOT EXISTS (SELECT 1 FROM regiao WHERE regiao_pais_id = v_pais AND regiao_nome = p_nomes(i));
    END LOOP;
  END regioes;
BEGIN
  regioes('Portugal', t_lista('Vinho Verde', 'Trás-os-Montes', 'Douro', 'Porto', 'Távora-Varosa', 'Dão', 'Bairrada',
                              'Beira Interior', 'Lisboa', 'Tejo', 'Península de Setúbal', 'Alentejo', 'Algarve',
                              'Madeira', 'Açores'));
  regioes('Espanha', t_lista('Rioja', 'Ribera del Duero', 'Rías Baixas', 'Priorat', 'Rueda', 'Toro', 'Navarra',
                             'Penedès', 'Jerez', 'Bierzo', 'La Mancha', 'Somontano', 'Jumilla', 'Montsant'));
  regioes('França', t_lista('Bordéus', 'Borgonha', 'Champagne', 'Vale do Loire', 'Vale do Ródano', 'Alsácia',
                            'Provença', 'Languedoc-Roussillon', 'Beaujolais', 'Cognac', 'Armagnac'));
  regioes('Itália', t_lista('Toscana', 'Piemonte', 'Veneto', 'Sicília', 'Puglia', 'Lombardia',
                            'Friuli-Venezia Giulia', 'Trentino-Alto Adige', 'Emilia-Romagna', 'Campania'));
  regioes('Escócia', t_lista('Speyside', 'Highlands', 'Islay', 'Lowlands', 'Campbeltown', 'Islands'));
  regioes('Inglaterra', t_lista('Londres', 'Kent', 'Sussex', 'Hampshire', 'Cornualha'));
  regioes('Estados Unidos da América', t_lista('Califórnia', 'Oregon', 'Washington', 'Nova Iorque', 'Texas',
                                               'Virgínia', 'Kentucky', 'Tennessee'));
END;
/

-- ============================================================
-- 3. MIGRAR OS PRODUTORES DO TEXTO PARA A REGIÃO e apagar a coluna de texto
--    (SQL dinâmico: a coluna antiga deixa de existir no fim, e o bloco tem de compilar também na 2.ª execução)
-- ============================================================

DECLARE
  v_existe NUMBER;
  v_cursor SYS_REFCURSOR;
  v_nome   VARCHAR2(200 CHAR);
  v_texto  VARCHAR2(200 CHAR);

  -- A região é procurada no país do próprio produtor.
  PROCEDURE migrar(p_texto VARCHAR2, p_regiao VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE
      'UPDATE produtor p SET p.produtor_regiao_id = ' ||
      '  (SELECT r.regiao_id FROM regiao r WHERE r.regiao_nome = :1 AND r.regiao_pais_id = p.produtor_pais_id) ' ||
      ' WHERE p.produtor_regiao = :2'
      USING p_regiao, p_texto;
  END migrar;
BEGIN
  SELECT COUNT(*) INTO v_existe FROM user_tab_columns
   WHERE table_name = 'PRODUTOR' AND column_name = 'PRODUTOR_REGIAO';
  IF v_existe = 0 THEN
    DBMS_OUTPUT.PUT_LINE('produtor_regiao (texto) já não existe: migração já feita.');
    RETURN;
  END IF;

  migrar('Douro', 'Douro');
  migrar('Alentejo', 'Alentejo');
  migrar('Vinho Verde — Melgaço', 'Vinho Verde');
  migrar('Bairrada', 'Bairrada');
  migrar('Arraiolos — Alentejo', 'Alentejo');
  migrar('Óbidos', 'Lisboa');
  migrar('Lisboa — Rossio', 'Lisboa');
  migrar('Algarve', 'Algarve');

  OPEN v_cursor FOR
    'SELECT produtor_nome, produtor_regiao FROM produtor ' ||
    ' WHERE produtor_regiao IS NOT NULL AND produtor_regiao_id IS NULL ORDER BY produtor_id';
  LOOP
    FETCH v_cursor INTO v_nome, v_texto;
    EXIT WHEN v_cursor%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('sem região (fica NULL): ' || v_nome || ' — "' || v_texto || '"');
  END LOOP;
  CLOSE v_cursor;

  EXECUTE IMMEDIATE 'ALTER TABLE produtor DROP COLUMN produtor_regiao';
END;
/

-- ============================================================
-- 4. FK COMPOSTA + CHECK (só depois de os dados estarem migrados)
-- ============================================================

DECLARE
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2264, -2275) THEN
        RAISE;
      END IF;
  END ddl;
BEGIN
  ddl('ALTER TABLE produtor ADD CONSTRAINT fk_produtor_regiao
         FOREIGN KEY (produtor_pais_id, produtor_regiao_id) REFERENCES regiao (regiao_pais_id, regiao_id)');
  ddl('ALTER TABLE produtor ADD CONSTRAINT ck_produtor_regiao_pais
         CHECK (produtor_regiao_id IS NULL OR produtor_pais_id IS NOT NULL)');
END;
/

COMMIT;
EXIT
