--------------------------------------------------------------------------------
-- AquaVitae — Patch incremental (2026-09-24)
-- Sessão renovável: o token de acesso (JWT) dura 60 min e a app não tinha como o renovar nem tratava um 401 a meio da
-- utilização — passada 1 hora os pedidos falhavam sem explicação. Tabela nova `utilizador_refresh_token`: um token opaco
-- (30 dias) que se troca por um novo par de tokens sem pedir a password; só o HASH fica guardado; cada renovação revoga o
-- token usado e emite outro (rotação).
--
-- Só correr numa BD de DEV criada antes deste patch (quem reconstruir do zero já tem a tabela em 01_tables.sql e a FK em
-- 02_constraints.sql). Tal como 04 a 14, NÃO faz parte do run-migrations. É repetível: se a tabela ou a FK já existem, ignora.
--
-- Uso manual (com NLS_LANG, ver database/README.md; no Git Bash, MSYS_NO_PATHCONV=1 nos dois comandos):
--   docker cp ddl/15_patch_refresh_token.sql aquavitae-oracle-xe:/tmp/15.sql
--   docker exec -e NLS_LANG=AMERICAN_AMERICA.AL32UTF8 aquavitae-oracle-xe sqlplus -s "<user>/<pass>@//localhost:1521/XEPDB1" @/tmp/15.sql
--------------------------------------------------------------------------------

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

DECLARE
  -- Ignora "já existe": ORA-00955 (a tabela), ORA-02275 (a FK) e ORA-01430 (a coluna).
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-955, -2275, -1430) THEN
        RAISE;
      END IF;
  END ddl;
BEGIN
  ddl('CREATE TABLE utilizador_refresh_token (
         refresh_token_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         utilizador_id                NUMBER NOT NULL,
         refresh_token_hash            VARCHAR2(64 CHAR) NOT NULL,
         refresh_token_criado_em       TIMESTAMP DEFAULT SYSTIMESTAMP,
         refresh_token_expira_em       TIMESTAMP NOT NULL,
         refresh_token_revogado_em     TIMESTAMP,
         refresh_token_revogado_motivo VARCHAR2(20 CHAR),
         CONSTRAINT uq_refresh_token_hash UNIQUE (refresh_token_hash)
       )');
  -- Para quem já correu a 1.ª versão deste patch (sem a coluna do motivo): ORA-01430 = a coluna já existe.
  ddl('ALTER TABLE utilizador_refresh_token ADD (refresh_token_revogado_motivo VARCHAR2(20 CHAR))');
  ddl('ALTER TABLE utilizador_refresh_token ADD CONSTRAINT fk_refresh_token_utilizador
         FOREIGN KEY (utilizador_id) REFERENCES utilizador (utilizador_id)');
  DBMS_OUTPUT.PUT_LINE('utilizador_refresh_token: ok');
END;
/

EXIT
